[package]
name = "stream"
version = "0.1.0"
edition = "2024"

[dependencies]
termimad = "0.34"
bat = "0.26.1"
streamdown-config = "0.1.3"
streamdown-parser = "0.1.3"
streamdown-render = "0.1.3"
syntect = "5.3.0"
terminal_size = "0.4"

[dev-dependencies]
