[package]
name = "stream"
version = "0.1.0"
edition = "2021"

[dependencies]
streamdown-parser = "0.1.3"
syntect = "5.3.0"
terminal_size = "0.4"
colored = "3.0.0"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "io-std", "macros"] }

[dev-dependencies]
